baseURL = "https://dragon-content.github.io/public/megakit/"
languageCode = 'en-us'
title = "Megakit"
Paginate = 20
PaginatePath = "/public/megakit/"
summaryLength = 10

[taxonomies]
category = "categories"

[permalinks]
posts = ":section/:year/:month/:day/:title/"

[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'